# application.yml
server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:@activatedProperties@}

cloud:
  config:
    server:
      git:
        uri: https://github.com/brunosantoslab/global-config
        clone-on-start: true
        username: '${BRUNOSANTOS_GIT_USER}'
        password: '${BRUNOSANTOS_GIT_PASSWORD}'

encrypt:
  key-store:
    location: ${BRUNOSANTOS_KEYSTORE_LOCATION}
    password: ${BRUNOSANTOS_KEYSTORE_PASSWORD} 
    alias: config-server-key                
    secret: ${BRUNOSANTOS_KEY_SECRET} 
